version: "3.7"

services:

  ideas_mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/database:/var/lib/mysql"
      - "./www:/var/www/"
    networks:
      - ideas_network

  ideas_apache:
    build: ./apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/var/www/"
    networks:
      - ideas_network

  ideas_php:
    build: 
      args:
        - user=laravel
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - "./mysql/database:/var/lib/mysql"
      - "./www:/var/www/"
    networks:
      - ideas_network

  ideas_redis:
    build: ./redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD='redispass'
    networks:
      - ideas_network

  ideas_phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - ideas_network

networks:
  ideas_network:
    driver: bridge
